if os.getenv("LOCAL_LUA_DEBUGGER_VSCODE") == "1" then
  require("lldebugger").start()
end
local Rope = require "Rope"

describe("A Rope should", function()
  it("retrieve chars from a single segment", function()
    local r = Rope.new()
    r:append_segment("abc")
    assert.are.same('a', r:get_char(1))
    assert.are.same('b', r:get_char(2))
    assert.are.same('c', r:get_char(3))
  end)
  it("seek between segments", function()
    local r = Rope.new()
    r:append_segment("foobar")
    r:append_segment("baz")
    assert.are.same('r', r:get_char(6))
    assert.are.same('b', r:get_char(7))
  end)
  it("seek over segments", function()
    local r = Rope.new()
    r:append_segment("foobar")
    r:append_segment("baz")
    r:append_segment("zot")
    assert.are.same('r', r:get_char(6))
    assert.are.same('t', r:get_char(12))
    assert.are.same('z', r:get_char(9))
    assert.are.same('a', r:get_char(8))
  end)
end)